import hashlib
import hmac
import json
import os
import smtplib
import subprocess
import time
from email.message import EmailMessage

REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
REDIS_QUEUE_KEY = os.getenv("REDIS_QUEUE_KEY", "mail_jobs")
JOB_HMAC_SECRET = os.getenv("JOB_HMAC_SECRET", "change_me")
SMTP_HOST = os.getenv("SMTP_HOST", "mailhog")
SMTP_PORT = int(os.getenv("SMTP_PORT", "1025"))
MAIL_FROM = os.getenv("MAIL_FROM", "reporter@lab.local")


def verify_signature(payload: dict, signature: str) -> bool:
    message = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    expected = hmac.new(JOB_HMAC_SECRET.encode("utf-8"), message, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


def send_report_email(recipient: str, payload: dict) -> None:
    msg = EmailMessage()
    msg["From"] = MAIL_FROM
    msg["To"] = recipient
    msg["Subject"] = "Daily Security Report"
    msg.set_content(
        "This is a demo report generated by worker.\n"
        f"Source: {payload.get('source')}\n"
        f"Requested at: {payload.get('requested_at')}\n"
    )

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as client:
        client.send_message(msg)


def pop_job_blocking(timeout_seconds: int = 5) -> str:
    result = subprocess.run(
        [
            "redis-cli",
            "-h",
            REDIS_HOST,
            "-p",
            REDIS_PORT,
            "BRPOP",
            REDIS_QUEUE_KEY,
            str(timeout_seconds),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    # redis-cli BRPOP output usually has two lines: key and value.
    lines = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if len(lines) < 2:
        return ""
    return lines[-1]


def run() -> None:
    while True:
        raw = pop_job_blocking()
        if not raw:
            continue

        try:
            envelope = json.loads(raw)
            payload = envelope["payload"]
            signature = envelope["signature"]
        except (json.JSONDecodeError, KeyError, TypeError):
            print("[worker] Dropped invalid job format")
            continue

        if not verify_signature(payload, signature):
            print("[worker] Dropped job with invalid signature")
            continue

        email = payload.get("email")
        if not isinstance(email, str) or "@" not in email:
            print("[worker] Dropped job with invalid email")
            continue

        try:
            send_report_email(email, payload)
            print(f"[worker] Sent report to {email}")
        except Exception as exc:
            print(f"[worker] Failed to send email: {exc}")
            time.sleep(1)


if __name__ == "__main__":
    run()
